resources:
  pipelines:
    - pipeline: linux
      source: sigmaris.linux
      trigger: true
    - pipeline: uboot
      source: sigmaris.u-boot
      trigger: true

trigger:
  batch: false
  branches:
    include:
      - master
      - ci-*
  tags:
    include:
      - '*-ci'

pool:
  vmImage: 'ubuntu-18.04'

steps:
- download: uboot
  artifact: mmc_u-boot
- download: linux
  artifact: linuxdebs
  patterns: '**/linux-image-*.deb'
- script: |
    set -e
    ls -l $(Pipeline.Workspace)/*
    cp $(Pipeline.Workspace)/uboot/mmc_u-boot/* $(Build.ArtifactStagingDirectory)
    rm $(Pipeline.Workspace)/linux/linuxdebs/linux-image-*-dbg_*_arm64.deb
    cp -r $(Pipeline.Workspace)/linux/linuxdebs $(Build.ArtifactStagingDirectory)
    sudo apt-get update
    sudo apt-get install -y bmap-tools curl debian-archive-keyring dosfstools e2fsprogs gdisk gzip libglib2.0-0 libgpgme11 libostree-1-1 parted qemu-system-x86 qemu-user-static systemd-container zsync
    sudo cp /usr/share/keyrings/debian-archive-keyring.gpg /etc/apt/trusted.gpg.d/debian-archive-keyring.gpg
    echo "deb http://deb.debian.org/debian testing main" | sudo tee /etc/apt/sources.list.d/debian-testing.list
    sudo apt-get update
    sudo apt-get install --no-install-recommends -y debos
    sudo debos --verbose --artifactdir="$(Build.ArtifactStagingDirectory)" recipes/buster-rockpro64.yaml
    sudo chown $(id -u):$(id -g) debian-buster-rockpro64.img
    gzip debian-buster-rockpro64.img
  displayName: Run debos to create image then gzip it
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'debian-buster-rockpro64.img.gz'
    artifactName: image
  displayName: Publish image as build artifact
