trigger:
  batch: false
  branches:
    include:
      - master
      - ci-*
  tags:
    include:
      - '*-ci'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo sed -i -e 's/xenial/bionic/g' /etc/apt/sources.list
    sudo apt-get update
    sudo apt-get install -y debian-archive-keyring
    sudo cp /usr/share/keyrings/debian-archive-keyring.gpg /etc/apt/trusted.gpg.d/debian-archive-keyring.gpg
    echo "deb http://deb.debian.org/debian testing main" | sudo tee /etc/apt/sources.list.d/debian-testing.list
    sudo apt-get update
    sudo apt-get install -y debos bmap-tools dosfstools e2fsprogs gdisk parted zsync
  displayName: Switch Ubuntu repo to bionic and add debian testing repository for debos
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'rock-builds'
    pipeline: 'sigmaris.u-boot'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'uboot'
    downloadPath: '$(Build.ArtifactStagingDirectory)'
  displayName: Download u-boot files
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'rock-builds'
    pipeline: 'sigmaris.linux'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'specific'
    itemPattern: 'linuxdebs/linux-image-*.deb'
    downloadPath: '$(Build.ArtifactStagingDirectory)'
  displayName: Download linux-image package
- script: |
    echo "Build.ArtifactStagingDirectory=$(Build.ArtifactStagingDirectory)"
    echo "System.ArtifactsDirectory=$(System.ArtifactsDirectory)"
    ls -lah "$(Build.ArtifactStagingDirectory)"/*
  displayName: What's in the staging directory?
