name: build

on:
  push:
    branches:
    - master
    - github-actions

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Install debos from debian testing repository
      run: |
        sudo apt-get update
        sudo apt-get install -y bmap-tools curl debian-archive-keyring dosfstools e2fsprogs gdisk libglib2.0-0 libgpgme11 libostree-1-1 parted qemu-system-x86 qemu-user-static systemd-container zsync
        sudo cp /usr/share/keyrings/debian-archive-keyring.gpg /etc/apt/trusted.gpg.d/debian-archive-keyring.gpg
        echo "deb http://deb.debian.org/debian testing main" | sudo tee /etc/apt/sources.list.d/debian-testing.list
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y debos

    - name: Download u-boot artifacts and run debos to create image
      run: |
        . build.manifest
        mkdir artifacts
        uboot_url_prefix="https://github.com/sigmaris/u-boot/releases/download/${UBOOT_RELEASE}"
        curl --location --output artifacts/idbloader.img "${uboot_url_prefix}/idbloader.img"
        curl --location --output artifacts/u-boot.itb    "${uboot_url_prefix}/u-boot.itb"
        sudo debos --verbose --artifactdir=artifacts --template-var="kernel_version:${KERNEL_VERSION}" recipes/buster-rockpro64.yaml
        sudo chown $(id -u):$(id -g) debian-buster-rockpro64.img

    - uses: actions/upload-artifact@v1.0.0
      with:
        name: rockpro64-image
        path: debian-buster-rockpro64.img
